language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - yarn install
script:
    - yarn build
cache:
    directories:
        - "node_modules"
notifications:
    email: true
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: src/.vuepress/dist
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    repo: cbourgois/cbourgois.github.io
    keep-history: true
    target-branch: master
    on:
        branch: master